# Generated by Django 4.2.1 on 2023-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_kdm', models.DateField(auto_now_add=True)),
                ('titulo_kdm', models.CharField(max_length=1028)),
                ('cpl_kdm', models.CharField(max_length=1028)),
                ('servidor_kdm', models.IntegerField()),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_clausura', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=1028)),
                ('version', models.CharField(max_length=1028)),
                ('cpl', models.CharField(blank=True, max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_ss', models.DateField(auto_now_add=True)),
                ('datetime_sesion', models.DateTimeField(blank=True, null=True)),
                ('titulo_sesion', models.CharField(max_length=1028)),
                ('version_sesion', models.CharField(blank=True, max_length=1028)),
                ('sala', models.CharField(choices=[('K1', 'Kursaal 1'), ('K2', 'Kursaal 2'), ('TVE', 'Teatro Victoria Eugenia')], max_length=1028)),
            ],
        ),
    ]
